import type { AdminDashboardData } from '../_types/admin.types'

export const adminDashboardData: AdminDashboardData = {
  stats: {
    activeUsers: 12450,
    totalTeachers: 842,
    monthlyRevenue: 84500,
    approvalQueue: 24,
    activeUsersChange: '+14% this month',
    teachersTrend: 'Steady',
    revenueChange: '+5.2% vs last month',
  },
  approvals: [
    {
      id: '1',
      courseTitle: 'Advanced React Patterns',
      instructorName: 'Jane Doe',
      instructorInitials: 'JD',
      category: 'Engineering',
      submittedAgo: 'Submitted 2 hours ago',
    },
    {
      id: '2',
      courseTitle: 'Introduction to Macroeconomics',
      instructorName: 'Adam Smith',
      instructorInitials: 'AS',
      category: 'Business',
      submittedAgo: 'Submitted 5 hours ago',
    },
    {
      id: '3',
      courseTitle: 'Digital Art Foundations',
      instructorName: 'Rachel Wong',
      instructorInitials: 'RW',
      category: 'Design',
      submittedAgo: 'Submitted 1 day ago',
    },
  ],
  activities: [
    {
      id: '1',
      icon: 'school',
      iconBg: 'bg-primary-container',
      iconColor: 'text-on-primary-container',
      text: '<span class="font-medium">New Course Published</span> by Prof. Davis',
      time: '10 mins ago',
    },
    {
      id: '2',
      icon: 'person_add',
      iconBg: 'bg-surface-container-high',
      iconColor: 'text-on-surface-variant',
      text: '<span class="font-medium">15 new students</span> enrolled in \'Data Science 101\'',
      time: '1 hour ago',
    },
    {
      id: '3',
      icon: 'payments',
      iconBg: 'bg-tertiary-container',
      iconColor: 'text-on-tertiary-container',
      text: '<span class="font-medium">Monthly payout</span> processed successfully.',
      time: '3 hours ago',
    },
    {
      id: '4',
      icon: 'report',
      iconBg: 'bg-error-container',
      iconColor: 'text-error',
      text: '<span class="font-medium">System Alert:</span> High server load detected during exams.',
      time: 'Yesterday',
      isLast: true,
    },
  ],
  revenueData: [
    { month: 'Jan', revenue: 42000 },
    { month: 'Feb', revenue: 38000 },
    { month: 'Mar', revenue: 51000 },
    { month: 'Apr', revenue: 46000 },
    { month: 'May', revenue: 58000 },
    { month: 'Jun', revenue: 72000 },
    { month: 'Jul', revenue: 68000 },
    { month: 'Aug', revenue: 79000 },
    { month: 'Sep', revenue: 84500 },
    { month: 'Oct', revenue: 92000 },
    { month: 'Nov', revenue: 88000 },
    { month: 'Dec', revenue: 95000 },
  ],
}
