/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicAuthRouteRouteImport } from './routes/_public/_auth/route'
import { Route as ProtectedDashboardRouteRouteImport } from './routes/_protected/dashboard/route'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as PublicCoursesCoursesRouteImport } from './routes/_public/_courses/courses'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/_auth/register'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/_auth/login'
import { Route as PublicAuthForgotPasswordRouteImport } from './routes/_public/_auth/forgotPassword'
import { Route as ProtectedDashboardCoursesRouteRouteImport } from './routes/_protected/dashboard/courses/route'
import { Route as ProtectedDashboardUsersIndexRouteImport } from './routes/_protected/dashboard/users/index'
import { Route as ProtectedDashboardStudentsIndexRouteImport } from './routes/_protected/dashboard/students/index'
import { Route as ProtectedDashboardSettingsIndexRouteImport } from './routes/_protected/dashboard/settings/index'
import { Route as ProtectedDashboardPaymentResultIndexRouteImport } from './routes/_protected/dashboard/payment-result/index'
import { Route as ProtectedDashboardEnrollmentsIndexRouteImport } from './routes/_protected/dashboard/enrollments/index'
import { Route as ProtectedDashboardCoursesIndexRouteImport } from './routes/_protected/dashboard/courses/index'
import { Route as ProtectedDashboardBuyCoursesIndexRouteImport } from './routes/_protected/dashboard/buy-courses/index'
import { Route as ProtectedDashboardCoursesIdRouteImport } from './routes/_protected/dashboard/courses/$id'
import { Route as ProtectedDashboardSettingsSecurityIndexRouteImport } from './routes/_protected/dashboard/settings/security/index'
import { Route as ProtectedDashboardSettingsProfileIndexRouteImport } from './routes/_protected/dashboard/settings/profile/index'
import { Route as ProtectedDashboardSettingsNotificationsIndexRouteImport } from './routes/_protected/dashboard/settings/notifications/index'
import { Route as ProtectedDashboardSettingsBillingIndexRouteImport } from './routes/_protected/dashboard/settings/billing/index'
import { Route as PublicCoursesIdCoursesIdRouteImport } from './routes/_public/_courses/_id/courses.$id'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthRouteRoute = PublicAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedDashboardRouteRoute = ProtectedDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedDashboardRouteRoute,
} as any)
const PublicCoursesCoursesRoute = PublicCoursesCoursesRouteImport.update({
  id: '/_courses/courses',
  path: '/courses',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const PublicAuthForgotPasswordRoute =
  PublicAuthForgotPasswordRouteImport.update({
    id: '/forgotPassword',
    path: '/forgotPassword',
    getParentRoute: () => PublicAuthRouteRoute,
  } as any)
const ProtectedDashboardCoursesRouteRoute =
  ProtectedDashboardCoursesRouteRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => ProtectedDashboardRouteRoute,
  } as any)
const ProtectedDashboardUsersIndexRoute =
  ProtectedDashboardUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => ProtectedDashboardRouteRoute,
  } as any)
const ProtectedDashboardStudentsIndexRoute =
  ProtectedDashboardStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => ProtectedDashboardRouteRoute,
  } as any)
const ProtectedDashboardSettingsIndexRoute =
  ProtectedDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => ProtectedDashboardRouteRoute,
  } as any)
const ProtectedDashboardPaymentResultIndexRoute =
  ProtectedDashboardPaymentResultIndexRouteImport.update({
    id: '/payment-result/',
    path: '/payment-result/',
    getParentRoute: () => ProtectedDashboardRouteRoute,
  } as any)
const ProtectedDashboardEnrollmentsIndexRoute =
  ProtectedDashboardEnrollmentsIndexRouteImport.update({
    id: '/enrollments/',
    path: '/enrollments/',
    getParentRoute: () => ProtectedDashboardRouteRoute,
  } as any)
const ProtectedDashboardCoursesIndexRoute =
  ProtectedDashboardCoursesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDashboardCoursesRouteRoute,
  } as any)
const ProtectedDashboardBuyCoursesIndexRoute =
  ProtectedDashboardBuyCoursesIndexRouteImport.update({
    id: '/buy-courses/',
    path: '/buy-courses/',
    getParentRoute: () => ProtectedDashboardRouteRoute,
  } as any)
const ProtectedDashboardCoursesIdRoute =
  ProtectedDashboardCoursesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ProtectedDashboardCoursesRouteRoute,
  } as any)
const ProtectedDashboardSettingsSecurityIndexRoute =
  ProtectedDashboardSettingsSecurityIndexRouteImport.update({
    id: '/settings/security/',
    path: '/settings/security/',
    getParentRoute: () => ProtectedDashboardRouteRoute,
  } as any)
const ProtectedDashboardSettingsProfileIndexRoute =
  ProtectedDashboardSettingsProfileIndexRouteImport.update({
    id: '/settings/profile/',
    path: '/settings/profile/',
    getParentRoute: () => ProtectedDashboardRouteRoute,
  } as any)
const ProtectedDashboardSettingsNotificationsIndexRoute =
  ProtectedDashboardSettingsNotificationsIndexRouteImport.update({
    id: '/settings/notifications/',
    path: '/settings/notifications/',
    getParentRoute: () => ProtectedDashboardRouteRoute,
  } as any)
const ProtectedDashboardSettingsBillingIndexRoute =
  ProtectedDashboardSettingsBillingIndexRouteImport.update({
    id: '/settings/billing/',
    path: '/settings/billing/',
    getParentRoute: () => ProtectedDashboardRouteRoute,
  } as any)
const PublicCoursesIdCoursesIdRoute =
  PublicCoursesIdCoursesIdRouteImport.update({
    id: '/_courses/_id/courses/$id',
    path: '/courses/$id',
    getParentRoute: () => PublicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRouteRouteWithChildren
  '/dashboard/courses': typeof ProtectedDashboardCoursesRouteRouteWithChildren
  '/forgotPassword': typeof PublicAuthForgotPasswordRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
  '/courses': typeof PublicCoursesCoursesRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/dashboard/courses/$id': typeof ProtectedDashboardCoursesIdRoute
  '/dashboard/buy-courses/': typeof ProtectedDashboardBuyCoursesIndexRoute
  '/dashboard/courses/': typeof ProtectedDashboardCoursesIndexRoute
  '/dashboard/enrollments/': typeof ProtectedDashboardEnrollmentsIndexRoute
  '/dashboard/payment-result/': typeof ProtectedDashboardPaymentResultIndexRoute
  '/dashboard/settings/': typeof ProtectedDashboardSettingsIndexRoute
  '/dashboard/students/': typeof ProtectedDashboardStudentsIndexRoute
  '/dashboard/users/': typeof ProtectedDashboardUsersIndexRoute
  '/courses/$id': typeof PublicCoursesIdCoursesIdRoute
  '/dashboard/settings/billing/': typeof ProtectedDashboardSettingsBillingIndexRoute
  '/dashboard/settings/notifications/': typeof ProtectedDashboardSettingsNotificationsIndexRoute
  '/dashboard/settings/profile/': typeof ProtectedDashboardSettingsProfileIndexRoute
  '/dashboard/settings/security/': typeof ProtectedDashboardSettingsSecurityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgotPassword': typeof PublicAuthForgotPasswordRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
  '/courses': typeof PublicCoursesCoursesRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/dashboard/courses/$id': typeof ProtectedDashboardCoursesIdRoute
  '/dashboard/buy-courses': typeof ProtectedDashboardBuyCoursesIndexRoute
  '/dashboard/courses': typeof ProtectedDashboardCoursesIndexRoute
  '/dashboard/enrollments': typeof ProtectedDashboardEnrollmentsIndexRoute
  '/dashboard/payment-result': typeof ProtectedDashboardPaymentResultIndexRoute
  '/dashboard/settings': typeof ProtectedDashboardSettingsIndexRoute
  '/dashboard/students': typeof ProtectedDashboardStudentsIndexRoute
  '/dashboard/users': typeof ProtectedDashboardUsersIndexRoute
  '/courses/$id': typeof PublicCoursesIdCoursesIdRoute
  '/dashboard/settings/billing': typeof ProtectedDashboardSettingsBillingIndexRoute
  '/dashboard/settings/notifications': typeof ProtectedDashboardSettingsNotificationsIndexRoute
  '/dashboard/settings/profile': typeof ProtectedDashboardSettingsProfileIndexRoute
  '/dashboard/settings/security': typeof ProtectedDashboardSettingsSecurityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRouteRouteWithChildren
  '/_public/_auth': typeof PublicAuthRouteRouteWithChildren
  '/_protected/dashboard/courses': typeof ProtectedDashboardCoursesRouteRouteWithChildren
  '/_public/_auth/forgotPassword': typeof PublicAuthForgotPasswordRoute
  '/_public/_auth/login': typeof PublicAuthLoginRoute
  '/_public/_auth/register': typeof PublicAuthRegisterRoute
  '/_public/_courses/courses': typeof PublicCoursesCoursesRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/dashboard/courses/$id': typeof ProtectedDashboardCoursesIdRoute
  '/_protected/dashboard/buy-courses/': typeof ProtectedDashboardBuyCoursesIndexRoute
  '/_protected/dashboard/courses/': typeof ProtectedDashboardCoursesIndexRoute
  '/_protected/dashboard/enrollments/': typeof ProtectedDashboardEnrollmentsIndexRoute
  '/_protected/dashboard/payment-result/': typeof ProtectedDashboardPaymentResultIndexRoute
  '/_protected/dashboard/settings/': typeof ProtectedDashboardSettingsIndexRoute
  '/_protected/dashboard/students/': typeof ProtectedDashboardStudentsIndexRoute
  '/_protected/dashboard/users/': typeof ProtectedDashboardUsersIndexRoute
  '/_public/_courses/_id/courses/$id': typeof PublicCoursesIdCoursesIdRoute
  '/_protected/dashboard/settings/billing/': typeof ProtectedDashboardSettingsBillingIndexRoute
  '/_protected/dashboard/settings/notifications/': typeof ProtectedDashboardSettingsNotificationsIndexRoute
  '/_protected/dashboard/settings/profile/': typeof ProtectedDashboardSettingsProfileIndexRoute
  '/_protected/dashboard/settings/security/': typeof ProtectedDashboardSettingsSecurityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/courses'
    | '/forgotPassword'
    | '/login'
    | '/register'
    | '/courses'
    | '/dashboard/'
    | '/dashboard/courses/$id'
    | '/dashboard/buy-courses/'
    | '/dashboard/courses/'
    | '/dashboard/enrollments/'
    | '/dashboard/payment-result/'
    | '/dashboard/settings/'
    | '/dashboard/students/'
    | '/dashboard/users/'
    | '/courses/$id'
    | '/dashboard/settings/billing/'
    | '/dashboard/settings/notifications/'
    | '/dashboard/settings/profile/'
    | '/dashboard/settings/security/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgotPassword'
    | '/login'
    | '/register'
    | '/courses'
    | '/dashboard'
    | '/dashboard/courses/$id'
    | '/dashboard/buy-courses'
    | '/dashboard/courses'
    | '/dashboard/enrollments'
    | '/dashboard/payment-result'
    | '/dashboard/settings'
    | '/dashboard/students'
    | '/dashboard/users'
    | '/courses/$id'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_public'
    | '/_protected/dashboard'
    | '/_public/_auth'
    | '/_protected/dashboard/courses'
    | '/_public/_auth/forgotPassword'
    | '/_public/_auth/login'
    | '/_public/_auth/register'
    | '/_public/_courses/courses'
    | '/_protected/dashboard/'
    | '/_protected/dashboard/courses/$id'
    | '/_protected/dashboard/buy-courses/'
    | '/_protected/dashboard/courses/'
    | '/_protected/dashboard/enrollments/'
    | '/_protected/dashboard/payment-result/'
    | '/_protected/dashboard/settings/'
    | '/_protected/dashboard/students/'
    | '/_protected/dashboard/users/'
    | '/_public/_courses/_id/courses/$id'
    | '/_protected/dashboard/settings/billing/'
    | '/_protected/dashboard/settings/notifications/'
    | '/_protected/dashboard/settings/profile/'
    | '/_protected/dashboard/settings/security/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_auth': {
      id: '/_public/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicAuthRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
    '/_public/_courses/courses': {
      id: '/_public/_courses/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof PublicCoursesCoursesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_auth/register': {
      id: '/_public/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_public/_auth/login': {
      id: '/_public/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_public/_auth/forgotPassword': {
      id: '/_public/_auth/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof PublicAuthForgotPasswordRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_protected/dashboard/courses': {
      id: '/_protected/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof ProtectedDashboardCoursesRouteRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
    '/_protected/dashboard/users/': {
      id: '/_protected/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof ProtectedDashboardUsersIndexRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
    '/_protected/dashboard/students/': {
      id: '/_protected/dashboard/students/'
      path: '/students'
      fullPath: '/dashboard/students/'
      preLoaderRoute: typeof ProtectedDashboardStudentsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
    '/_protected/dashboard/settings/': {
      id: '/_protected/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof ProtectedDashboardSettingsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
    '/_protected/dashboard/payment-result/': {
      id: '/_protected/dashboard/payment-result/'
      path: '/payment-result'
      fullPath: '/dashboard/payment-result/'
      preLoaderRoute: typeof ProtectedDashboardPaymentResultIndexRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
    '/_protected/dashboard/enrollments/': {
      id: '/_protected/dashboard/enrollments/'
      path: '/enrollments'
      fullPath: '/dashboard/enrollments/'
      preLoaderRoute: typeof ProtectedDashboardEnrollmentsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
    '/_protected/dashboard/courses/': {
      id: '/_protected/dashboard/courses/'
      path: '/'
      fullPath: '/dashboard/courses/'
      preLoaderRoute: typeof ProtectedDashboardCoursesIndexRouteImport
      parentRoute: typeof ProtectedDashboardCoursesRouteRoute
    }
    '/_protected/dashboard/buy-courses/': {
      id: '/_protected/dashboard/buy-courses/'
      path: '/buy-courses'
      fullPath: '/dashboard/buy-courses/'
      preLoaderRoute: typeof ProtectedDashboardBuyCoursesIndexRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
    '/_protected/dashboard/courses/$id': {
      id: '/_protected/dashboard/courses/$id'
      path: '/$id'
      fullPath: '/dashboard/courses/$id'
      preLoaderRoute: typeof ProtectedDashboardCoursesIdRouteImport
      parentRoute: typeof ProtectedDashboardCoursesRouteRoute
    }
    '/_protected/dashboard/settings/security/': {
      id: '/_protected/dashboard/settings/security/'
      path: '/settings/security'
      fullPath: '/dashboard/settings/security/'
      preLoaderRoute: typeof ProtectedDashboardSettingsSecurityIndexRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
    '/_protected/dashboard/settings/profile/': {
      id: '/_protected/dashboard/settings/profile/'
      path: '/settings/profile'
      fullPath: '/dashboard/settings/profile/'
      preLoaderRoute: typeof ProtectedDashboardSettingsProfileIndexRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
    '/_protected/dashboard/settings/notifications/': {
      id: '/_protected/dashboard/settings/notifications/'
      path: '/settings/notifications'
      fullPath: '/dashboard/settings/notifications/'
      preLoaderRoute: typeof ProtectedDashboardSettingsNotificationsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
    '/_protected/dashboard/settings/billing/': {
      id: '/_protected/dashboard/settings/billing/'
      path: '/settings/billing'
      fullPath: '/dashboard/settings/billing/'
      preLoaderRoute: typeof ProtectedDashboardSettingsBillingIndexRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
    '/_public/_courses/_id/courses/$id': {
      id: '/_public/_courses/_id/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof PublicCoursesIdCoursesIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface ProtectedDashboardCoursesRouteRouteChildren {
  ProtectedDashboardCoursesIdRoute: typeof ProtectedDashboardCoursesIdRoute
  ProtectedDashboardCoursesIndexRoute: typeof ProtectedDashboardCoursesIndexRoute
}

const ProtectedDashboardCoursesRouteRouteChildren: ProtectedDashboardCoursesRouteRouteChildren =
  {
    ProtectedDashboardCoursesIdRoute: ProtectedDashboardCoursesIdRoute,
    ProtectedDashboardCoursesIndexRoute: ProtectedDashboardCoursesIndexRoute,
  }

const ProtectedDashboardCoursesRouteRouteWithChildren =
  ProtectedDashboardCoursesRouteRoute._addFileChildren(
    ProtectedDashboardCoursesRouteRouteChildren,
  )

interface ProtectedDashboardRouteRouteChildren {
  ProtectedDashboardCoursesRouteRoute: typeof ProtectedDashboardCoursesRouteRouteWithChildren
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedDashboardBuyCoursesIndexRoute: typeof ProtectedDashboardBuyCoursesIndexRoute
  ProtectedDashboardEnrollmentsIndexRoute: typeof ProtectedDashboardEnrollmentsIndexRoute
  ProtectedDashboardPaymentResultIndexRoute: typeof ProtectedDashboardPaymentResultIndexRoute
  ProtectedDashboardSettingsIndexRoute: typeof ProtectedDashboardSettingsIndexRoute
  ProtectedDashboardStudentsIndexRoute: typeof ProtectedDashboardStudentsIndexRoute
  ProtectedDashboardUsersIndexRoute: typeof ProtectedDashboardUsersIndexRoute
  ProtectedDashboardSettingsBillingIndexRoute: typeof ProtectedDashboardSettingsBillingIndexRoute
  ProtectedDashboardSettingsNotificationsIndexRoute: typeof ProtectedDashboardSettingsNotificationsIndexRoute
  ProtectedDashboardSettingsProfileIndexRoute: typeof ProtectedDashboardSettingsProfileIndexRoute
  ProtectedDashboardSettingsSecurityIndexRoute: typeof ProtectedDashboardSettingsSecurityIndexRoute
}

const ProtectedDashboardRouteRouteChildren: ProtectedDashboardRouteRouteChildren =
  {
    ProtectedDashboardCoursesRouteRoute:
      ProtectedDashboardCoursesRouteRouteWithChildren,
    ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
    ProtectedDashboardBuyCoursesIndexRoute:
      ProtectedDashboardBuyCoursesIndexRoute,
    ProtectedDashboardEnrollmentsIndexRoute:
      ProtectedDashboardEnrollmentsIndexRoute,
    ProtectedDashboardPaymentResultIndexRoute:
      ProtectedDashboardPaymentResultIndexRoute,
    ProtectedDashboardSettingsIndexRoute: ProtectedDashboardSettingsIndexRoute,
    ProtectedDashboardStudentsIndexRoute: ProtectedDashboardStudentsIndexRoute,
    ProtectedDashboardUsersIndexRoute: ProtectedDashboardUsersIndexRoute,
    ProtectedDashboardSettingsBillingIndexRoute:
      ProtectedDashboardSettingsBillingIndexRoute,
    ProtectedDashboardSettingsNotificationsIndexRoute:
      ProtectedDashboardSettingsNotificationsIndexRoute,
    ProtectedDashboardSettingsProfileIndexRoute:
      ProtectedDashboardSettingsProfileIndexRoute,
    ProtectedDashboardSettingsSecurityIndexRoute:
      ProtectedDashboardSettingsSecurityIndexRoute,
  }

const ProtectedDashboardRouteRouteWithChildren =
  ProtectedDashboardRouteRoute._addFileChildren(
    ProtectedDashboardRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRouteRoute: typeof ProtectedDashboardRouteRouteWithChildren
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRouteRoute: ProtectedDashboardRouteRouteWithChildren,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicAuthRouteRouteChildren {
  PublicAuthForgotPasswordRoute: typeof PublicAuthForgotPasswordRoute
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
}

const PublicAuthRouteRouteChildren: PublicAuthRouteRouteChildren = {
  PublicAuthForgotPasswordRoute: PublicAuthForgotPasswordRoute,
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
}

const PublicAuthRouteRouteWithChildren = PublicAuthRouteRoute._addFileChildren(
  PublicAuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAuthRouteRoute: typeof PublicAuthRouteRouteWithChildren
  PublicCoursesCoursesRoute: typeof PublicCoursesCoursesRoute
  PublicCoursesIdCoursesIdRoute: typeof PublicCoursesIdCoursesIdRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthRouteRoute: PublicAuthRouteRouteWithChildren,
  PublicCoursesCoursesRoute: PublicCoursesCoursesRoute,
  PublicCoursesIdCoursesIdRoute: PublicCoursesIdCoursesIdRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
