/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardsRouteRouteImport } from './routes/_protected/dashboards/route'
import { Route as ProtectedDashboardsIndexRouteImport } from './routes/_protected/dashboards/index'
import { Route as PublicCoursesCoursesRouteImport } from './routes/_public/_courses/courses'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/_auth/register'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/_auth/login'
import { Route as PublicAuthForgotPasswordRouteImport } from './routes/_public/_auth/forgotPassword'
import { Route as ProtectedDashboardsCoursesRouteRouteImport } from './routes/_protected/dashboards/courses/route'
import { Route as ProtectedDashboardsStudentsIndexRouteImport } from './routes/_protected/dashboards/students/index'
import { Route as ProtectedDashboardsSettingsIndexRouteImport } from './routes/_protected/dashboards/settings/index'
import { Route as ProtectedDashboardsCoursesIndexRouteImport } from './routes/_protected/dashboards/courses/index'
import { Route as ProtectedDashboardsCoursesIdRouteImport } from './routes/_protected/dashboards/courses/$id'
import { Route as ProtectedDashboardsSettingsSecurityIndexRouteImport } from './routes/_protected/dashboards/settings/security/index'
import { Route as ProtectedDashboardsSettingsNotificationsIndexRouteImport } from './routes/_protected/dashboards/settings/notifications/index'
import { Route as ProtectedDashboardsSettingsBillingIndexRouteImport } from './routes/_protected/dashboards/settings/billing/index'
import { Route as PublicCoursesIdCoursesIdRouteImport } from './routes/_public/_courses/_id/courses.$id'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardsRouteRoute =
  ProtectedDashboardsRouteRouteImport.update({
    id: '/dashboards',
    path: '/dashboards',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDashboardsIndexRoute =
  ProtectedDashboardsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDashboardsRouteRoute,
  } as any)
const PublicCoursesCoursesRoute = PublicCoursesCoursesRouteImport.update({
  id: '/_courses/courses',
  path: '/courses',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAuthForgotPasswordRoute =
  PublicAuthForgotPasswordRouteImport.update({
    id: '/_auth/forgotPassword',
    path: '/forgotPassword',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const ProtectedDashboardsCoursesRouteRoute =
  ProtectedDashboardsCoursesRouteRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => ProtectedDashboardsRouteRoute,
  } as any)
const ProtectedDashboardsStudentsIndexRoute =
  ProtectedDashboardsStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => ProtectedDashboardsRouteRoute,
  } as any)
const ProtectedDashboardsSettingsIndexRoute =
  ProtectedDashboardsSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => ProtectedDashboardsRouteRoute,
  } as any)
const ProtectedDashboardsCoursesIndexRoute =
  ProtectedDashboardsCoursesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDashboardsCoursesRouteRoute,
  } as any)
const ProtectedDashboardsCoursesIdRoute =
  ProtectedDashboardsCoursesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ProtectedDashboardsCoursesRouteRoute,
  } as any)
const ProtectedDashboardsSettingsSecurityIndexRoute =
  ProtectedDashboardsSettingsSecurityIndexRouteImport.update({
    id: '/settings/security/',
    path: '/settings/security/',
    getParentRoute: () => ProtectedDashboardsRouteRoute,
  } as any)
const ProtectedDashboardsSettingsNotificationsIndexRoute =
  ProtectedDashboardsSettingsNotificationsIndexRouteImport.update({
    id: '/settings/notifications/',
    path: '/settings/notifications/',
    getParentRoute: () => ProtectedDashboardsRouteRoute,
  } as any)
const ProtectedDashboardsSettingsBillingIndexRoute =
  ProtectedDashboardsSettingsBillingIndexRouteImport.update({
    id: '/settings/billing/',
    path: '/settings/billing/',
    getParentRoute: () => ProtectedDashboardsRouteRoute,
  } as any)
const PublicCoursesIdCoursesIdRoute =
  PublicCoursesIdCoursesIdRouteImport.update({
    id: '/_courses/_id/courses/$id',
    path: '/courses/$id',
    getParentRoute: () => PublicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboards': typeof ProtectedDashboardsRouteRouteWithChildren
  '/dashboards/courses': typeof ProtectedDashboardsCoursesRouteRouteWithChildren
  '/forgotPassword': typeof PublicAuthForgotPasswordRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
  '/courses': typeof PublicCoursesCoursesRoute
  '/dashboards/': typeof ProtectedDashboardsIndexRoute
  '/dashboards/courses/$id': typeof ProtectedDashboardsCoursesIdRoute
  '/dashboards/courses/': typeof ProtectedDashboardsCoursesIndexRoute
  '/dashboards/settings/': typeof ProtectedDashboardsSettingsIndexRoute
  '/dashboards/students/': typeof ProtectedDashboardsStudentsIndexRoute
  '/courses/$id': typeof PublicCoursesIdCoursesIdRoute
  '/dashboards/settings/billing/': typeof ProtectedDashboardsSettingsBillingIndexRoute
  '/dashboards/settings/notifications/': typeof ProtectedDashboardsSettingsNotificationsIndexRoute
  '/dashboards/settings/security/': typeof ProtectedDashboardsSettingsSecurityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgotPassword': typeof PublicAuthForgotPasswordRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
  '/courses': typeof PublicCoursesCoursesRoute
  '/dashboards': typeof ProtectedDashboardsIndexRoute
  '/dashboards/courses/$id': typeof ProtectedDashboardsCoursesIdRoute
  '/dashboards/courses': typeof ProtectedDashboardsCoursesIndexRoute
  '/dashboards/settings': typeof ProtectedDashboardsSettingsIndexRoute
  '/dashboards/students': typeof ProtectedDashboardsStudentsIndexRoute
  '/courses/$id': typeof PublicCoursesIdCoursesIdRoute
  '/dashboards/settings/billing': typeof ProtectedDashboardsSettingsBillingIndexRoute
  '/dashboards/settings/notifications': typeof ProtectedDashboardsSettingsNotificationsIndexRoute
  '/dashboards/settings/security': typeof ProtectedDashboardsSettingsSecurityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_protected/dashboards': typeof ProtectedDashboardsRouteRouteWithChildren
  '/_protected/dashboards/courses': typeof ProtectedDashboardsCoursesRouteRouteWithChildren
  '/_public/_auth/forgotPassword': typeof PublicAuthForgotPasswordRoute
  '/_public/_auth/login': typeof PublicAuthLoginRoute
  '/_public/_auth/register': typeof PublicAuthRegisterRoute
  '/_public/_courses/courses': typeof PublicCoursesCoursesRoute
  '/_protected/dashboards/': typeof ProtectedDashboardsIndexRoute
  '/_protected/dashboards/courses/$id': typeof ProtectedDashboardsCoursesIdRoute
  '/_protected/dashboards/courses/': typeof ProtectedDashboardsCoursesIndexRoute
  '/_protected/dashboards/settings/': typeof ProtectedDashboardsSettingsIndexRoute
  '/_protected/dashboards/students/': typeof ProtectedDashboardsStudentsIndexRoute
  '/_public/_courses/_id/courses/$id': typeof PublicCoursesIdCoursesIdRoute
  '/_protected/dashboards/settings/billing/': typeof ProtectedDashboardsSettingsBillingIndexRoute
  '/_protected/dashboards/settings/notifications/': typeof ProtectedDashboardsSettingsNotificationsIndexRoute
  '/_protected/dashboards/settings/security/': typeof ProtectedDashboardsSettingsSecurityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboards'
    | '/dashboards/courses'
    | '/forgotPassword'
    | '/login'
    | '/register'
    | '/courses'
    | '/dashboards/'
    | '/dashboards/courses/$id'
    | '/dashboards/courses/'
    | '/dashboards/settings/'
    | '/dashboards/students/'
    | '/courses/$id'
    | '/dashboards/settings/billing/'
    | '/dashboards/settings/notifications/'
    | '/dashboards/settings/security/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgotPassword'
    | '/login'
    | '/register'
    | '/courses'
    | '/dashboards'
    | '/dashboards/courses/$id'
    | '/dashboards/courses'
    | '/dashboards/settings'
    | '/dashboards/students'
    | '/courses/$id'
    | '/dashboards/settings/billing'
    | '/dashboards/settings/notifications'
    | '/dashboards/settings/security'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_public'
    | '/about'
    | '/_protected/dashboards'
    | '/_protected/dashboards/courses'
    | '/_public/_auth/forgotPassword'
    | '/_public/_auth/login'
    | '/_public/_auth/register'
    | '/_public/_courses/courses'
    | '/_protected/dashboards/'
    | '/_protected/dashboards/courses/$id'
    | '/_protected/dashboards/courses/'
    | '/_protected/dashboards/settings/'
    | '/_protected/dashboards/students/'
    | '/_public/_courses/_id/courses/$id'
    | '/_protected/dashboards/settings/billing/'
    | '/_protected/dashboards/settings/notifications/'
    | '/_protected/dashboards/settings/security/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboards': {
      id: '/_protected/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof ProtectedDashboardsRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboards/': {
      id: '/_protected/dashboards/'
      path: '/'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof ProtectedDashboardsIndexRouteImport
      parentRoute: typeof ProtectedDashboardsRouteRoute
    }
    '/_public/_courses/courses': {
      id: '/_public/_courses/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof PublicCoursesCoursesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_auth/register': {
      id: '/_public/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_auth/login': {
      id: '/_public/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_auth/forgotPassword': {
      id: '/_public/_auth/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof PublicAuthForgotPasswordRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/dashboards/courses': {
      id: '/_protected/dashboards/courses'
      path: '/courses'
      fullPath: '/dashboards/courses'
      preLoaderRoute: typeof ProtectedDashboardsCoursesRouteRouteImport
      parentRoute: typeof ProtectedDashboardsRouteRoute
    }
    '/_protected/dashboards/students/': {
      id: '/_protected/dashboards/students/'
      path: '/students'
      fullPath: '/dashboards/students/'
      preLoaderRoute: typeof ProtectedDashboardsStudentsIndexRouteImport
      parentRoute: typeof ProtectedDashboardsRouteRoute
    }
    '/_protected/dashboards/settings/': {
      id: '/_protected/dashboards/settings/'
      path: '/settings'
      fullPath: '/dashboards/settings/'
      preLoaderRoute: typeof ProtectedDashboardsSettingsIndexRouteImport
      parentRoute: typeof ProtectedDashboardsRouteRoute
    }
    '/_protected/dashboards/courses/': {
      id: '/_protected/dashboards/courses/'
      path: '/'
      fullPath: '/dashboards/courses/'
      preLoaderRoute: typeof ProtectedDashboardsCoursesIndexRouteImport
      parentRoute: typeof ProtectedDashboardsCoursesRouteRoute
    }
    '/_protected/dashboards/courses/$id': {
      id: '/_protected/dashboards/courses/$id'
      path: '/$id'
      fullPath: '/dashboards/courses/$id'
      preLoaderRoute: typeof ProtectedDashboardsCoursesIdRouteImport
      parentRoute: typeof ProtectedDashboardsCoursesRouteRoute
    }
    '/_protected/dashboards/settings/security/': {
      id: '/_protected/dashboards/settings/security/'
      path: '/settings/security'
      fullPath: '/dashboards/settings/security/'
      preLoaderRoute: typeof ProtectedDashboardsSettingsSecurityIndexRouteImport
      parentRoute: typeof ProtectedDashboardsRouteRoute
    }
    '/_protected/dashboards/settings/notifications/': {
      id: '/_protected/dashboards/settings/notifications/'
      path: '/settings/notifications'
      fullPath: '/dashboards/settings/notifications/'
      preLoaderRoute: typeof ProtectedDashboardsSettingsNotificationsIndexRouteImport
      parentRoute: typeof ProtectedDashboardsRouteRoute
    }
    '/_protected/dashboards/settings/billing/': {
      id: '/_protected/dashboards/settings/billing/'
      path: '/settings/billing'
      fullPath: '/dashboards/settings/billing/'
      preLoaderRoute: typeof ProtectedDashboardsSettingsBillingIndexRouteImport
      parentRoute: typeof ProtectedDashboardsRouteRoute
    }
    '/_public/_courses/_id/courses/$id': {
      id: '/_public/_courses/_id/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof PublicCoursesIdCoursesIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface ProtectedDashboardsCoursesRouteRouteChildren {
  ProtectedDashboardsCoursesIdRoute: typeof ProtectedDashboardsCoursesIdRoute
  ProtectedDashboardsCoursesIndexRoute: typeof ProtectedDashboardsCoursesIndexRoute
}

const ProtectedDashboardsCoursesRouteRouteChildren: ProtectedDashboardsCoursesRouteRouteChildren =
  {
    ProtectedDashboardsCoursesIdRoute: ProtectedDashboardsCoursesIdRoute,
    ProtectedDashboardsCoursesIndexRoute: ProtectedDashboardsCoursesIndexRoute,
  }

const ProtectedDashboardsCoursesRouteRouteWithChildren =
  ProtectedDashboardsCoursesRouteRoute._addFileChildren(
    ProtectedDashboardsCoursesRouteRouteChildren,
  )

interface ProtectedDashboardsRouteRouteChildren {
  ProtectedDashboardsCoursesRouteRoute: typeof ProtectedDashboardsCoursesRouteRouteWithChildren
  ProtectedDashboardsIndexRoute: typeof ProtectedDashboardsIndexRoute
  ProtectedDashboardsSettingsIndexRoute: typeof ProtectedDashboardsSettingsIndexRoute
  ProtectedDashboardsStudentsIndexRoute: typeof ProtectedDashboardsStudentsIndexRoute
  ProtectedDashboardsSettingsBillingIndexRoute: typeof ProtectedDashboardsSettingsBillingIndexRoute
  ProtectedDashboardsSettingsNotificationsIndexRoute: typeof ProtectedDashboardsSettingsNotificationsIndexRoute
  ProtectedDashboardsSettingsSecurityIndexRoute: typeof ProtectedDashboardsSettingsSecurityIndexRoute
}

const ProtectedDashboardsRouteRouteChildren: ProtectedDashboardsRouteRouteChildren =
  {
    ProtectedDashboardsCoursesRouteRoute:
      ProtectedDashboardsCoursesRouteRouteWithChildren,
    ProtectedDashboardsIndexRoute: ProtectedDashboardsIndexRoute,
    ProtectedDashboardsSettingsIndexRoute:
      ProtectedDashboardsSettingsIndexRoute,
    ProtectedDashboardsStudentsIndexRoute:
      ProtectedDashboardsStudentsIndexRoute,
    ProtectedDashboardsSettingsBillingIndexRoute:
      ProtectedDashboardsSettingsBillingIndexRoute,
    ProtectedDashboardsSettingsNotificationsIndexRoute:
      ProtectedDashboardsSettingsNotificationsIndexRoute,
    ProtectedDashboardsSettingsSecurityIndexRoute:
      ProtectedDashboardsSettingsSecurityIndexRoute,
  }

const ProtectedDashboardsRouteRouteWithChildren =
  ProtectedDashboardsRouteRoute._addFileChildren(
    ProtectedDashboardsRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedDashboardsRouteRoute: typeof ProtectedDashboardsRouteRouteWithChildren
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardsRouteRoute: ProtectedDashboardsRouteRouteWithChildren,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAuthForgotPasswordRoute: typeof PublicAuthForgotPasswordRoute
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
  PublicCoursesCoursesRoute: typeof PublicCoursesCoursesRoute
  PublicCoursesIdCoursesIdRoute: typeof PublicCoursesIdCoursesIdRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthForgotPasswordRoute: PublicAuthForgotPasswordRoute,
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
  PublicCoursesCoursesRoute: PublicCoursesCoursesRoute,
  PublicCoursesIdCoursesIdRoute: PublicCoursesIdCoursesIdRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
