import type { StudentsPageData } from '#/schemas/student'

export const studentsPageData: StudentsPageData = {
  students: [
    {
      id: '1',
      name: 'Emma Thompson',
      studentId: '2024-001',
      email: 'emma.thompson@edupro.edu',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAz27K9M8HtgMxGkJ7llYdPtYp4F-NtBCgzIsUU6sq9aqN7bFRO0ipXKKEXJVgJBG2x4uxdyf3pnpmfknyMekTnCKHqAkTFAjmAXi2o-HF1GDKQRr-ApB35b6XzIVv3ZEwncZtPGeyHiWau1FRyceoUcpHKLaI00ZASEegrHfkDNsAfwVkS5VDad-kRrqhbNhKtFRY2VMh9cGaWm2vQL91sxgiQbKi365kCjo4CsJkodIQYYOXKoNrlpeU8Lef3xqRK2mUTgW2TMMYB',
      initials: 'ET',
      enrolledCourses: [
        { name: 'CS 101', progress: 78 },
        { name: 'MATH 202', progress: 65 },
      ],
      lastActive: '2 hours ago',
      status: 'ACTIVE',
    },
    {
      id: '2',
      name: 'Michael Chen',
      studentId: '2024-042',
      email: 'michael.chen@edupro.edu',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAzukUslgt0sQpWrwW8CQWmhSBdATgEtuLLgbPu-d72PE3AW5qEP458CooYoL180hiig0dGf7r2iXkSAco_nVeNfX_FZBkFHSGfch-031OLiptgCBfa4zycNQOwZSwzh15p13reYeS6T66QfRVcKHQfdQaggapdpWM88o5UQqwCg5k01uk6F7CAV-H3GvNLx3pRR2yy7CaKEmlUD33A1QQlyIjX-dAhnbH1P8kBVYZB7PMhFmdZxhjmgszv4EPGFXA1rSkyZ1ANovfB',
      initials: 'MC',
      enrolledCourses: [
        { name: 'PHYS 101', progress: 42 },
      ],
      lastActive: 'Yesterday',
      status: 'ACTIVE',
    },
    {
      id: '3',
      name: 'Sarah Jenkins',
      studentId: '2024-018',
      email: 'sarah.jenkins@edupro.edu',
      initials: 'SJ',
      enrolledCourses: [
        { name: 'LIT 105', progress: 15 },
        { name: 'HIST 201', progress: 30 },
        { name: 'ART 101', progress: 10 },
      ],
      lastActive: '3 weeks ago',
      status: 'INACTIVE',
    },
    {
      id: '4',
      name: 'David Garcia',
      studentId: '2024-089',
      email: 'david.garcia@edupro.edu',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAEA60LjiJiT8lh2fqX33xUhculWxHeCr7j5aFf9zk5q9BRS5Qp75ONk4dotFmxlL52B_-xJ5i6aINyOBN66rhLbGd0djZgpoh62h1EZ8E_2wfR5nlWAvzF5zsEQteQ2Y6ofrdAzw_7A2O6F_SEMlG_9yIWy1DZdNghCO8AyOEwlpwpJfpyRHw27jahuz2Uf5OSkcieMW1DSiaMEZXOIHzXGTHErb27aEvaD0UcIHjP6KrMAfJVIOF2TXWdjLk35-QpMtXSmvRYU7qo',
      initials: 'DG',
      enrolledCourses: [
        { name: 'MATH 202', progress: 95 },
        { name: 'ENG 101', progress: 88 },
      ],
      lastActive: 'Just now',
      status: 'ACTIVE',
    },
    {
      id: '5',
      name: 'Aisha Patel',
      studentId: '2024-056',
      email: 'aisha.patel@edupro.edu',
      initials: 'AP',
      enrolledCourses: [
        { name: 'CS 101', progress: 55 },
        { name: 'PHYS 101', progress: 60 },
        { name: 'MATH 201', progress: 72 },
      ],
      lastActive: '5 days ago',
      status: 'ACTIVE',
    },
    {
      id: '6',
      name: 'James Wilson',
      studentId: '2024-033',
      email: 'james.wilson@edupro.edu',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAmgRiN1l-pdm5idfgXJo-OUL_Mex_l_5xT4WHHd-3d7E_Xqy9XNpXdwCI-cuTmdHaFlnXBW9fOlJkuUKcoCuPeAkJGBj-9aruJMaKa2E1JJzRnn1naMknVLKSIB0E7d2C5TF4wtR6NdUpiKmg9U6yQ4J8qwm7NeyRqFjnQygZW0CnfV2coZ1R-HhqEj2QOM2enmzRXK0ksxI_StNLqvg0v-XD2LsZ4obKGttLGoFe6XSjlhXCglawD-QXOmZA6aMCZm5myHERRbWju',
      initials: 'JW',
      enrolledCourses: [
        { name: 'BIO 101', progress: 23 },
      ],
      lastActive: '1 week ago',
      status: 'INACTIVE',
    },
    {
      id: '7',
      name: 'Priya Sharma',
      studentId: '2024-071',
      email: 'priya.sharma@edupro.edu',
      initials: 'PS',
      enrolledCourses: [
        { name: 'CS 201', progress: 81 },
        { name: 'MATH 301', progress: 74 },
        { name: 'PHYS 201', progress: 69 },
      ],
      lastActive: '1 hour ago',
      status: 'ACTIVE',
    },
    {
      id: '8',
      name: 'Lucas Brown',
      studentId: '2024-104',
      email: 'lucas.brown@edupro.edu',
      initials: 'LB',
      enrolledCourses: [
        { name: 'ENG 101', progress: 45 },
        { name: 'HIST 101', progress: 38 },
      ],
      lastActive: '2 weeks ago',
      status: 'INACTIVE',
    },
  ],
  totalCount: 128,
}
